### ISSUE TITLE
Spring Rest Docs + Junit 학습 및 예제를 이용한 사이드 프로젝트

### ISSUE THREAD

**Issue by ShinsRo** [YAPP-16th/Team_Android_1_Client#17]
@hscom96 @siotman 

Refference:
- [스프링 레스트 독스 공식 문서 및 샘플 예제](https://docs.spring.io/spring-restdocs/docs/2.0.4.RELEASE/reference/html5/)
- [배달의 민족 기술 블로그: Spring Rest Docs 적용](https://woowabros.github.io/experience/2018/12/28/spring-rest-docs.html)

Spring Rest Docs 기술 요구에 따라 백엔드 학습 스터디를 진행할 필요성이 있습니다.
구상하고 있는 방법은 아래와 같습니다.

1. 금요일(21일)까지 각자 충실히 공부
2. 금요일, 정한 시간에 행아웃을 통하여 함께 예제 코딩 진행. [약 2시간]
3. 주제 : 메모장 CRUD 구현(DB는 인메모리 ^^)과 Rest Docs를 이용한 API 문서 만들기

주제를 어떻게 구현하면 좋을지를 중심으로 구현해보면 좋을 것 같습니다.
현수님 의견 여쭤요. 시간이랑, 내용에 대해서 의견 코멘트 해주세요.

**Comment by hscom96** [comment]
네 알겠습니다. 주제에서 메모장 CRUD라는건 이해가 안가는데 정확히 어떤걸 말씀하시는 건가요?

**Comment by hscom96** [comment]
네 알겠습니다. 
rest docs가 테스트코드 기반으로 생성되는 것이기 때문에 
테스트코드 작성에 대한 지식 없이는 진행이 힘들꺼라 생각합니다.
그래도 얕게 알기는 해서 진행을 한다면 
일단 간단한 item같은 crud에 대한 문서를 작성하는 법으로 진행하면 좋을꺼 같습니다.

**Comment by ShinsRo** [comment]
네~ 금요일 되는 시간 슬랙 DM 주세요. 시간 비워놓을게요.
