### ISSUE TITLE
Rest API 설계조건에 대한 학습

### ISSUE THREAD

**Issue by hscom96** [YAPP-16th/Team_Android_1_Client#18]
이미 알고 계실 수도 있겠지만 이번 프로젝트 진행하면서  
Rest API의 정확한 요구조건에 맞춰서 설계하는거 어떤가요? 
특히 self-descriptive, hateous는 잘 만족시키지 못한다고 합니다.
이 부분을 꼭 신경써서 했으면 좋을꺼 같습니다. 
참고하기 좋은 자료 공유합니다. 

1.   RESTful API 설계 가이드
https://sanghaklee.tistory.com/57

2. 그런 REST API로 괜찮은가 (네이버 deview) 
https://youtu.be/RP_f5dMoHFc

**Comment by ShinsRo** [comment]
아~ 좋습니다.
읽어보고 실 프로젝트에도 컨벤션 지켜볼게요 :)

실제 개발에서도 서로 PR 검토해주고, 안지켜지는게 있으면 노션 주기로해요.

**Comment by hscom96** [comment]
서로 검토해주는거 좋습니다 ㅎㅎ

**Comment by ShinsRo** [comment]
근데 아래 부분, 
버전 관리 FM으로 하려면 프록시 써야되는데 여기까지 범위 잡으실건가요?

### 9.2. URI Versioning 개발 가이드
- 개발 코드에서 버저닝 정보를 관리하지 않는다.
- 개발 프로젝트 폴더의 버저닝은 VCS(e.g. git)를 이용한다. 
v1(v1 branch), v2(master branch)

- 웹 서버의 reverse-proxy 기능을 활용한다
  - 웹 APP 서버의 라우팅은 버저닝을 제외하고 개발한다. /users, /posts
  - http://api.test.com/v1 -> (reverse-proxy) -> 웹 APP /

  - 시나리오 case(Node.js express server)
    - v1 process
      - app-name: v1
      - port: 3001
      - dir: /home/v1
      - Apache ProxyPassReverse “/v1” “http://127.0.0.1:3001”
      - Nginx location /v1 {proxy_pass http://127.0.0.1:3001}

     - v2 process
       - app-name: v2
       - port: 3002
       - dir: /home/v2
       - Apache ProxyPassReverse “/v2” “http://127.0.0.1:3002”
       - Nginx location /v2 {proxy_pass http://127.0.0.1:3002}

API 버저닝 여부에 관계없이 프로젝트 구조가 변경되지 않는다.



출처: https://sanghaklee.tistory.com/57 [이상학의 개발블로그]

**Comment by hscom96** [comment]
흠..... 저 부분은 일단 생각하지 말까요?
