### ISSUE TITLE
인터렉티브 한 UI 제공을 위한 사전조사 해보기

### ISSUE THREAD

**Issue by islandparadise14** [YAPP-16th/Team_Android_1_Client#30]
아는거 있으면 다같이 공유해봅시다

**Comment by jsh-me** [comment]
1. https://android-arsenal.com/
2. https://kmshack.github.io/AndroidUICollection/
원하는게 이게 맞는가 싶네요 한 번 들어가서 확인해보세요:)
제가 자주 애용하는 사이트는 1번이고,
2번은 번쩍번쩍 간지나는 UI가 많아서 공유해봅니다.
