### ISSUE TITLE
api 스펙 정의 - 기능 리스트업

### ISSUE THREAD

**Issue by islandparadise14** [YAPP-16th/Team_Android_1_Client#41]
본격적인 작업의 시작

**Comment by islandparadise14** [comment]
https://docs.google.com/document/d/1qr-EgXe1nN-3AoDvIu7rgT6C5cy9EtqLi51LqKb9Bv4/edit

**Comment by ShinsRo** [comment]
[API 문서](https://drive.google.com/drive/u/1/folders/1z7fKax2Hl9btVs3XzskO28lPZRmQh_9n)
