### ISSUE TITLE
백엔드 프로젝트 패키지 구조에 대한 논의

### ISSUE THREAD

**Issue by ShinsRo** [YAPP-16th/Team_Android_1_Client#5]
현수님, 백엔드 프로젝트 구조에 대해서 의견 여쭙습니다.
방법은 크게 두가지 중 하나일 것 같아요.

1. FeatureBy
> ex)
root/
|--configs
|--features
|--|--기능1
|--|--|--controller
|--|--|--domain
|--...
|--utils
|--...
2. LayerBy
>ex)
root/
|--configs
|--controller
|--domain

제생각에는 FeatureBy가 왠만하면 깔끔할 것 같은데, 어때요, 현수님?

**Comment by hscom96** [comment]
네 1번방법으로 가죠~ 단순 계층으로만 분류하면 다른기능이랑 섞이기 때문에 기능별로 분류 하는 방식이 나은 것 같습니다. 
이와 관련해서 제가 예전에 봤던 자료인데 https://12bme.tistory.com/271 
다음 게시물과 같이 정확히는 테이블 중심으로, 비슷한 테이블들은 한 패키지로 구성하고 
그 하위 패키지에는 계층간 분류 방식을 쓰면 괜찮을것 같습니다.

**Comment by ShinsRo** [comment]
아~ 좋은 레퍼런스입니다.

그럼 features.table.* 패키징으로 네이밍하는 것으로 알고, 이슈 클로즈 하겠습니다.

Refferd:
  - https://12bme.tistory.com/271
