### ISSUE TITLE
시장 및 유사 서비스 분석

### ISSUE THREAD

**Issue by subak94** [YAPP-16th/Team_Android_1_Client#7]

**Comment by ShinsRo** [comment]
비움박스 기능과 조금 다르지만, "불필요한 물품을 대신 처리한다"는 관점에서 비슷한 앱이 있어 코멘트 남깁니다.

[중고 물품 처리 앱, 주마](https://apps.apple.com/kr/app/%EC%A3%BC%EB%A7%88-zooma/id1099061702)

@subak94
